### PR TITLE
Add TCP as transport protocol

### PR DESCRIPTION
**Pull request by Gaulomatic**
Extraction of protocol related functionality in seperate projects. Addition of TCP transport layer.

I did this because frickin' Xamarin.Mac throws a `NotImplementedException` in the ctor of the `NamedPipeClientStream` class.

### CODE REVIEW

**Comment by jacqueskang** [comment]
@Gaulomatic Thanks for your proposal, but I need some time to analyze this PR because I see it's introducing breaking changes by converting IpcServiceClient into abstracted class and adding PipeIpcServiceClient and TcpIpcServiceClient. I'm wondering if it's better to keep the client class be awareness of the protocol using behind: when switching from one protocol to another, just change the configuration somehow instead of changing the client type (similar to WCF)...

**Comment by Gaulomatic** [comment]
I agree, using a specific `.Add<Protocol>Ipc()` extension method with applicable configuration options would be better and in some cases simply needed. Currently the `.Build()` method is doing all the heavy lifting of configuration. I will make changes accordingly.

Speaking of configuration, here is what I think after playing with the TcpClient: The `IpcServiceHost` class with it's threading stuff is getting in touch with things that should be the concern of the protocol provider. I have another branch I am currently working on to enable bi-directional messaging and I have to override the complete `.Run()` method in order to make the TcpClient work best. And then the circle is closing: Because the `IpcServiceOptions.ThreadCount` setting no longer makes sense is would be better aligned with the Pipe provider.

So, to address your concern regarding breaking changes, I would say they are unavoidable to make things work nicely. The threading stuff and stream handling (currently the TCP client opens a connection for every request..) needs to be the concern of the provider.

**Comment by jacqueskang** [comment]
@Gaulomatic regarding configuration, I think it would be nice to achieve something like
```csharp
    services
        .AddIpc(builder => builder
            .AddNamedPipeEndpoint(options =>
            {
                options.PipeName = "pipeName";
                options.ThreadCount = 2;
            })
            .AddTcpEndpoint(options => {
                options.Port = 12345;
                // other settings
            })
        );
```
Currently the pipe name was passed through IpcServiceHostBuilder.Build which is a bad design.

I still prefer not making breaking changes since V1 is already published and there are few consumers, unless we integreate the tcp features in V2. But otherwise I would happy to accept annotating existing methods with ObsoleteAttribute, providing a hint for making update.

**Comment by jacqueskang** [comment]
If you agree, I can create a new branch with my proposal for extending the framework with other protocols.

**Comment by Gaulomatic** [comment]
Yes, that would be nice. Your approach with adding (potentially multiple) endpoints is much more powerful than what I had in mind. I will integrate your branch with mine.

**Comment by Gaulomatic** [comment]
Currently I am tinkering with a way to enable (simple) bidirectional messaging. I would like to transport notifications to the client over the already established TCP connection. For my use case broadcasts are sufficient since I only have one connected client.

Maybe this would be a useful addition for an incoming version bump. Let me know what you think about this.

**Comment by jacqueskang** [comment]
Would you consider using SingalR or some think like RabbitMQ for bidirectional messaging? I don't really feel like addressing this scenario in this project to avoid the complexity.

**Comment by Gaulomatic** [comment]
Yes, I already thought to use something like that. And then I came across your library. It's so much more lightweight and easy to use. That said, as soon as the transport providers are pluggable I should be able to write a custom provider and wrapper for my personal needs which support that.

**Comment by jacqueskang** [comment]
@Gaulomatic I have now a branch custom-transport-protocol, could you please have a look and comment?

**Comment by Gaulomatic** [comment]
I have added the TCP endpoint at [here](https://github.com/Gaulomatic/IpcServiceFramework/tree/custom-transport-protocol). The TCP client still makes a dedicated connection for each request but in a local environment this should be okay. The reason is because the stream gets disposed and on a network stream this "kills" the connection. So the "connect for each request" attempt is plain simple and should not impact performance all too much.

**Comment by jacqueskang** [comment]
looks good! would you create a PR and I'll add some tests before creating a new release, thanks

**Comment by Gaulomatic** [comment]
PR is [here](https://github.com/jacqueskang/IpcServiceFramework/pull/24).

**Comment by jacqueskang** [comment]
Thanks! I'll probably publish v1.1.0 tomorrow with this change included

**Comment by Gaulomatic** [comment]
Thanks to Xamarin, their Mono codebase seems to be a little bit outdated :-)

**Pull request closed without merging**
