### PR TITLE
Add support for SSL

### PR DESCRIPTION
**Pull request by gsuberland**
This PR adds support for IPC over SSL. The server can load an X509Certificate2 object as the certificate, and the client can either rely upon the system certificate validation or implement a custom validation callback.

I have included code in the ConsoleClient, ConsoleServer, and WebServer projects to provide examples of using the `SslIpcServiceClient` and `SslIpcServiceEndpoint` classes. There are testing certificates included.

Usage information and security guidance has been added to the readme.

While the code doesn't currently implement client certificates, it was written with the expectation that this functionality could be added later.

### CODE REVIEW

**Comment by gsuberland** [comment]
This is a first pass approach that gets the feature up and working.

I realised this morning that there's a somewhat more elegant and extensible approach to this. Instead of duplicating most of the class code for the TCP transport, I could instead modify the TCP classes with an overloaded constructor to take a `Func<Stream, Stream>` that wraps a user-specified stream around the `NetworkStream`. The SSL feature would then be a set of convenience classes wrapped around this, offering the same API as this PR does.

The bonus of the stream wrapping approach is that users can provide their own wrapping stream for whatever purposes they like. For example, if the user wished to implement a custom handshake outside of the normal IPC mechanism, they could subclass `Stream` and do so.

Assuming this feature is something you're interested in, I'm now in two minds as to whether we should merge this to get the initial SSL feature set in and rework towards the stream-wrapping model later, or do the rework before merging anything. Let me know what you think.

**Comment by jacqueskang** [comment]
@gsuberland Thanks for your suggestion and PR! 
Indeed, SSL basically only makes sens for TCP and I would prefere it be an option on the existing Tcp endpoint/client. Creating new SSL endpoint/client types seems not be DRY enough for me.

**Comment by gsuberland** [comment]
Agreed. I'll rework this so that it's a constructor overload on the TCP classes, offering either SSL or a `Func<Stream, Stream>` for custom stream wrappers.

**Comment by gsuberland** [comment]
Added PFX file in new PR.

**Pull request merged**
