### PR TITLE
Create NamedPipe with Everyone Access on Windows Platform

### PR DESCRIPTION
**Pull request by brightness007**
The IPC pipe created by windows service could not be accessed by other processes. It is due to the permission settings of the pipe.

The solution is passing proper security handle when creating pipe. The native method is called since .netstandard does not support it so far.

This modification only affect Windows platform.

### CODE REVIEW

**Comment by jacqueskang** [comment]
@brightness007 thanks for you contribution but I cannot reproduce the issue that you are trying to resolve.

**Comment by InfinityGhost** [comment]
> @brightness007 thanks for you contribution but I cannot reproduce the issue that you are trying to resolve.

I managed to reproduce the issue by creating a Windows service in .NET Core that uses namedpipes for IPC, then registering the app as a Windows Service.

1. Server HostBuilder

Requires `Microsoft.Extensions.Hosting.WindowsServices` NuGet package

```cs
IHostBuilder host = Host.CreateDefaultBuilder().
    ConfigureServices(services => 
    {
        services.AddScoped<ISomeContract, ISomeImplemention>();
    })
    .ConfigureIpcHost(builder => 
    {
        builder.AddNamedPipeEndpoint<ISomeContract>("SomeContractEndpoint");
    })
    .UseWindowsService(); // Makes the process usable as a Windows service
```

2. Setting up service and starting

In Powershell:
```powershell
New-Service -Name "SomeService" -BinaryPathName "path/to/server/binary.exe"
Start-Service -Name "SomeService"
```

From this point forward, any client that tries to access the named pipe endpoint will crash with a `System.UnauthorizedAccessException`. Starting the server binary will work without issue.

```
An exception of type 'System.UnauthorizedAccessException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Access to the path is denied.'
   at System.IO.Pipes.NamedPipeClientStream.TryConnect(Int32 timeout, CancellationToken cancellationToken)
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.<>c__DisplayClass20_0.<ConnectAsync>b__0()
   at ...
```

I haven't tested yet if this PR resolves this issue on Windows.
However, the same issue exists if you run the same server executable without `.UseWindowsService()` built for Linux as root and try to access it from a lesser privileged user client application.

**Comment by brightness007** [comment]
Sorry for reply so late.

The code looks OK to me.

The process is running with the current user when the binary is launched directly (by double click). No issue is found.

For Windows Service,  New-Service will create a service with "SYSTEM" user by default. On Windows platform, two processes running with different account could not talk to each other. That is why System.UnauthorizedAccessException is thrown.
.Net platform does not provide API to modify RPC security settings, even in .Net Core. My PR is aimed to solve this problem.

These security API are only available on Windows platform, and the RuntimeInformation.IsOSPlatform(OSPlatform.Windows) is checked. For  Linux, the security should be controlled by umask, which could be modified in code.

Sorry for my poor English.

Regards,
Peng ZHANG

________________________________

**Comment by jacqueskang** [comment]
Thank you @brightness007 for your contribution and sorry for the delay of my review.

**Pull request merged**
